#!/bin/sh /etc/rc.common
# /etc/init.d
# Copyright (C) 2008 OpenWrt.org   

START=50
STOP=80

# use procd start
USE_PROCD=1

DAEMON=osmanage
PROG=/etc/osmanage/$DAEMON


start_service() {
	echo "start $DAEMON  service!"
	# add instance
	procd_open_instance
	procd_set_param respawn 5 1 -1
	procd_set_param command $PROG
	procd_append_param command -DW
	procd_close_instance
}
stop_service() {
	echo "stop $DAEMON service!"
	killall -9 $DAEMON
}

reload_service(){
	echo "reload $DAEMON  service!"
	stop
	start
}

restart() {
	stop
	start
}